# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14.0.1
      uses: actions/setup-java@v1
      with:
        java-version: 14.0.1
    - name: Build executable JAR with Maven
      run: mvn clean compile assembly:single
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdfAnalyzerExectuable.zip
        path: target/pdfAnalyzer-1.0-SNAPSHOT-jar-with-dependencies.jar
